# Generated by Django 3.2.6 on 2021-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_notebook',
            field=models.ManyToManyField(blank=True, to='magaz.Notebook', verbose_name='Тавары'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_smartphone',
            field=models.ManyToManyField(blank=True, to='magaz.Smartphone', verbose_name='Тавары'),
        ),
    ]
