# Generated by Django 3.2.6 on 2021-09-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0004_auto_20210830_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='magaz.brand'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='magaz.brand'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='cores',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('iOS', 'iOS'), ('MUi', 'MUi')], max_length=100, verbose_name='Операционная система'),
        ),
    ]
