# Generated by Django 3.2.6 on 2021-09-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0005_auto_20210902_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaz.brand'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaz.brand'),
        ),
    ]
